#mandatory
updatepages = false

#optional
downloaders = 1

#optional
processors = 1

#optional - Default is unlinited (-1)
#this or 'maxdatasize' must be set to a positive value
#maxpages = 100

#optional - Default is unlinited (-1)
maxredirects = 500

#optional - Default is unlinited (-1)
#this or 'maxpages' must be set to a positive value
#size is measured in bytes
maxdatasize = 1000001000

#mandatory
datapath="data"

#mandatory
#separated by semicolons ';'
valid_tlds="edu"

#mandatory
#separated by semicolons ';'
valid_extensions="html;shtml;txt"

#mandatory
seedlist = '''
http://www.ucr.edu/
http://www.stanford.edu
http://www.mit.edu
https://www.yale.edu
https://www.princeton.edu
https://www.uoregon.edu
https://www.byu.edu
https://www.columbia.edu
https://www.duke.edu
https://www.jhu.edu
http://www.palomar.edu
http://www.valleycollege.edu
http://www.rcc.edu
http://www.rccd.edu
http://www.redlands.edu
http://www.sdcity.edu
http://www.sdmesa.edu
http://www.sdsu.edu
http://www.sandiego.edu
http://www.craftonhills.edu
'''
